# Generated by Django 6.0.3 on 2026-03-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('pin_hash', models.CharField(max_length=64)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('food', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('accommodation', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('transport', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('savings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
