# Generated by Django 6.0.3 on 2026-04-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pin_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
